### ISSUE TITLE
Improve WASI SDK experience for C

### ISSUE THREAD

**Issue by itowlson** [deislabs/generator-wasm-oci#10]
C to WASI compilation relies on the WASI SDK.  The C language instructions have a placeholder about the hardwired SDK path in the makefile, but we should do better - e.g. install SDK, provide instructions for installing SDK, detect SDK and put in correct path, _something_.

**Comment by technosophos** [comment]
I started a separate issue on this, then realized it was a duplicate.

I do like the idea of having an SDK copy local to the project. It has a few upsides:

- Easier for the user
- No need to synchronize the library across all your projects

It would also be nice to add the library to the `.gitignore` and add a separate target for just installing that library. That way it can be checked into Git without bloat, but also easily re-retched on a new installation
