### ISSUE TITLE
Rust: No instructions or assistance on building the binary

### ISSUE THREAD

**Issue by technosophos** [deislabs/generator-wasm-oci#17]
The `C` version builds a nice `Makefile` that I invoke with just `make`, and the instructions say that quite clearly.

But with Rust, I am left to my own devices. While the notes do tell me that I need to install wasm32-wasi, they do not tell me what to do with the target.

Options:

1. Write the build script for the user. A `Makefile` might be nice for the consistency, or a `Justfile` or a Cargo plugin or whatever.
2. Just write a clear `cargo build --target wasm32-wasi --release` instruction in the generator

**Comment by itowlson** [comment]
Good point.  The VS Code `tasks` file provides both `Build Native` and `Build WASM` tasks, and of course both GitHub workflows build the WASM file, but we should include explicit instructions for local build without VS Code.

**Comment by technosophos** [comment]
Ugh... I didn't even think of using the VS Code task to do it. 🤦
